version: '3.9'

services:
  app:
    build: .
    image: gboeing/osmnx:latest
    container_name: osm-print-tool
    volumes:
      - .:/app
    working_dir: /app
    command: python main.py
    environment:
      - TZ=Asia/Tokyo
    stdin_open: true
    tty: true
